# Copyright 2022 LieberLieber Software GmbH 
# Author: Daniel Siegl
# Description: BUild the MTIP.sln and the Setup after each commit.

name: Build MTIP.sln
on: [push]
jobs:
  build:
    runs-on: [self-hosted, pcs]
    timeout-minutes: 15
    
    steps:
     - name: Checkout Code
       uses: actions/checkout@v1
     
     - name: Setup MSBuild Path
       uses: microsoft/setup-msbuild@v1.1
        
     - name: Build Solution
       run: msbuild MTIP.sln /p:Configuration=Release

     - name: Publish Binary Artifact
       uses: actions/upload-artifact@v3
       with:
          name: mtip-sparx-installer
          path: .\MTIPInstaller\Release\*.msi
          retention-days: 5
       
     